### ISSUE TITLE
go.mod module name

### ISSUE THREAD

**Issue by jh125486** [mellium/sasl#6]
Is there a reason that the module name is `mellium.im/sasl` in `go.mod`?

It's playing havoc with Go 1.12 modules since this is hosted on `github.com/mellium/sasl`.

```bash
go: github.com/mellium/sasl@v0.2.1: parsing go.mod: unexpected module path "mellium.im/sasl"
go: error loading module requirements
```

**Comment by SamWhited** [comment]
This is the correct module name and the hosting metatag is setup correctly to point to the GitHub.
More information is needed to figure out the error you're seeing, can you provide me with a way to reproduce the problem? What commands did you run to get that error? Since you appear to have the go.mod file already, that makes me think you must have connected to GitHub correctly to fetch it.

**Comment by jh125486** [comment]
Yes, I was trying to import it through the github URL.   My proxy blocks `mellium.im` unfortunately.

**Comment by SamWhited** [comment]
That's not how imports work in Go, you need to import using the name of the module.

Unfortunately, your proxy is doing the wrong thing here. IP ranking isn't actually a valid way to track malware across the internet, especially on IPv4 where NAT is prevalent. I will look into moving off of Netlify or getting my own IP, but no promises. You need to update your proxy or complain to your network administrator, they're doing something wrong and dangerous that's going to lead to more false positives like this.

**Comment by SamWhited** [comment]
I should also mention that if you need a temporary work around, vendoring or adding a `replace` directive to your projects `go.mod` file are options that will still work. Then you can manually fetch the source yourself from GitHub and still import it with the correct module name.

**Comment by kishaningithub** [comment]
I don't see why it is so hard to replace mellium.im to github link in this repo

**Comment by SamWhited** [comment]
> I don't see why it is so hard to replace mellium.im to github link in this repo. This would take care of several concerns.

People are already using the other import, if I change it their projects will be broken.

Also, it won't really take care of anyone's concerns because GitHub also has problems and blocks people from accessing their IPs sometimes (eg. due to U.S. export laws).

The answer to address the problems brought up here is for me to get a dedicated IP, if anyone has suggestions for services that I could use I would appreciate it. Unfortunately, I make no money off of this library so they probably have to be free or very cheap.
